import type { APIRoute } from 'astro';
import { getCollection } from 'astro:content';
import { pages, llmsPreamble } from '../data/site-pages';
// Generated by scripts/prepare-feeds.mjs — see sitemap.xml.ts.
import staticMeta from '../data/static-meta.json';

// Generated, replacing the hand-maintained llms.txt that shipped through
// 66e8000. Everything above "## Core Pages" is the preamble carried verbatim;
// Core Pages and Recent Articles are derived, so a new article reaches the
// agentic surface with nothing to remember.

const SITE = 'https://aicoachellavalley.org';

const human = (d: Date) =>
  d.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    timeZone: 'UTC',
  });

export const GET: APIRoute = async () => {
  const articles = (await getCollection('news'))
    .filter((a) => !a.data.draft)
    .sort((a, b) => b.data.date.getTime() - a.data.date.getTime());

  // Titles come from each page's own <title>; the label is the short human
  // name, the blurb is the manifest's richer prose.
  const labels: Record<string, string> = {
    '/': 'Homepage',
    '/events': 'Events',
    '/philanthropy': 'Philanthropy',
    '/pledge': 'Responsible AI Pledge',
  };

  const core = pages
    .map((p) => {
      if (!(staticMeta as Record<string, unknown>)[p.file]) {
        throw new Error(`[llms.txt] no extracted metadata for public/${p.file}`);
      }
      const label = labels[p.path] ?? p.path;
      return `- [${label}](${SITE}${p.path}) — ${p.llms}`;
    })
    .join('\n');

  let out = `${llmsPreamble}

## Core Pages

${core}
- [Intelligence Network (.com)](https://aicoachellavalley.com) — the agent-native companion with nodes, briefs, and reports
- [llms.txt (.com)](https://aicoachellavalley.com/llms.txt) — machine-readable summary of the Intelligence Network
`;

  if (articles.length > 0) {
    const list = articles
      .map(
        (a) =>
          `- [${a.data.title}](${SITE}/news/${a.id}) — ${human(a.data.date)}. ${a.data.description}`,
      )
      .join('\n');

    out += `
## News

Editorial coverage of AI in the Coachella Valley — what is happening, and why it matters here. Index at ${SITE}/news. RSS at ${SITE}/news/rss.xml.

${list}
`;
  }

  return new Response(out, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
};
