import type { APIRoute } from 'astro';
import { getCollection } from 'astro:content';
import { pages } from '../data/site-pages';
// Generated by scripts/prepare-feeds.mjs, which also fails the build if any
// page in public/ is unaccounted for or has lost its title/description.
import staticMeta from '../data/static-meta.json';

// Generated, replacing the hand-maintained sitemap.xml that shipped through
// 66e8000. This permanently closes "Next .org Cleanup Cycle" item 4 (stale
// lastmods): article lastmods are now derived, and the four static entries are
// the only hand-bumped values left.

const SITE = 'https://aicoachellavalley.org';

const iso = (d: Date) => d.toISOString().slice(0, 10);

export const GET: APIRoute = async () => {
  // Belt and braces: prepare-feeds.mjs already failed the build if a page lost
  // its metadata, but a sitemap entry for a page with no title is worse than a
  // failed build, so assert here too.
  for (const p of pages) {
    if (!(staticMeta as Record<string, unknown>)[p.file]) {
      throw new Error(`[sitemap] no extracted metadata for public/${p.file}`);
    }
  }

  const articles = (await getCollection('news'))
    .filter((a) => !a.data.draft)
    .sort((a, b) => b.data.date.getTime() - a.data.date.getTime());

  const entries: Array<{
    loc: string;
    lastmod: string;
    changefreq: string;
    priority: string;
  }> = [
    ...pages.map((p) => ({
      loc: SITE + (p.path === '/' ? '/' : p.path),
      lastmod: p.lastmod,
      changefreq: p.changefreq,
      priority: p.priority.toFixed(1),
    })),
  ];

  // The /news index only enters the sitemap once there is something on it.
  if (articles.length > 0) {
    entries.push({
      loc: `${SITE}/news`,
      lastmod: iso(articles[0].data.updated ?? articles[0].data.date),
      changefreq: 'weekly',
      priority: '0.8',
    });
    for (const a of articles) {
      entries.push({
        loc: `${SITE}/news/${a.id}`,
        lastmod: iso(a.data.updated ?? a.data.date),
        changefreq: 'monthly',
        priority: '0.6',
      });
    }
  }

  const body =
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    entries
      .map(
        (e) =>
          `  <url>\n` +
          `    <loc>${e.loc}</loc>\n` +
          `    <lastmod>${e.lastmod}</lastmod>\n` +
          `    <changefreq>${e.changefreq}</changefreq>\n` +
          `    <priority>${e.priority}</priority>\n` +
          `  </url>`,
      )
      .join('\n') +
    `\n</urlset>\n`;

  return new Response(body, {
    headers: { 'Content-Type': 'application/xml; charset=utf-8' },
  });
};
